### ISSUE TITLE
Too low accuracy

### ISSUE THREAD

**Issue by mugenggeng** [cg1177/DCAN#4]
Excuse me, why did I get a low accuracy after training and testing according to your method

**Comment by mugenggeng** [comment]
mAP at tIoU 0.1 is 0.7184708874933091
mAP at tIoU 0.2 is 0.6910493253734883
mAP at tIoU 0.3 is 0.6523199517814122
mAP at tIoU 0.4 is 0.5964088928349324
mAP at tIoU 0.5 is 0.5201558475817378
mAP at tIoU 0.6 is 0.4196229250109158
mAP at tIoU 0.7 is 0.3085124834642902
mAP at tIoU 0.8 is 0.18811028051123077
mAP at tIoU 0.9 is 0.05531092062872859

**Comment by mugenggeng** [comment]
Excuse me, I would also like to ask whether AR@AN selects the first K proposals to calculate regression through setting the parameter max_avg_nr_proposals

**Comment by cg1177** [comment]
Hello, I was working on some other projects before, so I just saw your issue.

> Excuse me, why did I get a low accuracy after training and testing according to your method.

Unstable performance due to small dataset. You can try to run the training procedure multiple times.

> Excuse me, I would also like to ask whether AR@AN selects the first K proposals to calculate regression through setting the parameter max_avg_nr_proposals.

The evaluation program is derived from the official, we have not modified it. You can view the evaluation code for details.
